### ISSUE TITLE
Error when trying to test with vitest

### ISSUE THREAD

**Issue by david10sing** [bvaughn/react-resizable-panels#460]
👋 

I am trying to test the following using `vitest` and getting the error below.

```
test('Imperative handle works', () => {
    const ref = React.createRef<ImperativePanelHandle>()

    act(() => {
      root.render(
        <PanelGroup direction='horizontal'>
          <Panel ref={ref} defaultSize={50}>
            A
          </Panel>
          <PanelResizeHandle />
          <Panel defaultSize={50}>B</Panel>
        </PanelGroup>
      )
    })

    console.log(ref.current?.getId())
    const el = document.body.querySelector(
      `[data-panel-id="${ref.current?.getId()}"]`
    )
    expect(el).toBeInTheDocument()
    expect(el).toHaveTextContent('A')
    console.log()

    expect(ref.current?.getSize()).toEqual(50)
})
```

> Error: Panel size not found for panel ":r1:"
 ❯ assert node_modules/react-resizable-panels/dist/react-resizable-panels.development.node.esm.js:675:11
    673|   if (!expectedCondition) {
    674|     console.error(message);
    675|     throw Error(message);
       |           ^
    676|   }
    677| }
 ❯ node_modules/react-resizable-panels/dist/react-resizable-panels.development.node.esm.js:1739:5
 ❯ Object.getSize node_modules/react-resizable-panels/dist/react-resizable-panels.development.node.esm.js:118:14

- Has anyone tried using vitest to test `react-resizable-panels`?
- Is there something I might be missing from the test environment setup?

**Comment by bvaughn** [comment]
Can you share a minimal repro please? (Something I can check out and run)

**Comment by bvaughn** [comment]
Okay here's a minimal repro:

### `package.json`
```json
{
  "name": "temp-vitetest",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "vitest"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "react": "^19.0.0",
    "react-dom": "^19.0.0",
    "react-resizable-panels": "^2.0.22"
  },
  "devDependencies": {
    "@testing-library/react": "^14.2.1",
    "@vitejs/plugin-react": "^4.3.1",
    "jsdom": "^24.0.0",
    "vitest": "^1.3.0"
  }
}
```

### `vite.config.js`
```js
import { defineConfig } from "vite";
import react from "@vitejs/plugin-react";

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [react()],
  test: {
    globals: true,
    environment: "jsdom",
    parallel: true,
  },
});
```

### `src/example.test.ts`
```ts
import { render } from "@testing-library/react";
import { createElement, createRef } from "react";
import { Panel, PanelGroup, PanelResizeHandle } from "react-resizable-panels";
import { expect, test } from "vitest";

test("Imperative handle works", () => {
  const ref = createRef();

  render(
    createElement(
      PanelGroup,
      {
        direction: "horizontal",
      },
      createElement(Panel, { defaultSize: 50, ref }, "A"),
      createElement(PanelResizeHandle),
      createElement(Panel, { defaultSize: 50 }, "B")
    )
  );

  const el = document.body.querySelector(
    `[data-panel-id="${ref.current?.getId()}"]`
  );
  expect(el?.parentElement).toBeDefined();
  expect(el?.textContent).toBe("A");
  expect(ref.current?.getSize()).toEqual(50);
});
```

**Comment by bvaughn** [comment]
Looks like this is because Vitetest is running the Node build target (which makes sense) but then that build target doesn't run layout effects (which also makes sense, from React's POV– as this is intended to just be the server-rendering portion) _but_ that means that Panel's never "mount" and register themselves, which means tests won't work in that sense.

**Comment by bvaughn** [comment]
Perhaps you could try running your tests in [Vitetest's "Browser Mode"](https://vitest.dev/guide/browser/)?

**Comment by bvaughn** [comment]
### `package.json`
```json
{
  "name": "temp-vitetest",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "vitest"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "react": "^19.0.0",
    "react-dom": "^19.0.0",
    "react-resizable-panels": "^2.0.22"
  },
  "devDependencies": {
    "@testing-library/react": "^14.2.1",
    "@vitejs/plugin-react": "^4.3.1",
    "@vitest/browser": "beta",
    "jsdom": "^24.0.0",
    "playwright": "^1.45.1",
    "vitest": "beta"
  }
}
```

### `vite.config.ts`
```ts
import { defineConfig } from "vitest/config";
import react from "@vitejs/plugin-react";

export default defineConfig({
  plugins: [react()],
});
```

### `vite.workspace.ts`
```ts
import { defineWorkspace } from "vitest/config";

export default defineWorkspace([
  {
    test: {
      // an example of file based convention,
      // you don't have to follow it
      include: ["src/**/*.{test,spec}.ts", "src/**/*.{test,spec}.tsx"],
      name: "browser",
      browser: {
        enabled: true,
        instances: [{ browser: "headless" }],
      },
    },
  },
]);
```

**Comment by bvaughn** [comment]
Should be resolved in the next release, via 84df2088ee7cf3277ac2f3f96acf62204db5c01c

**Comment by bvaughn** [comment]
Fix published as react-resizable-panels@3.0.0; give it another try

**Comment by david10sing** [comment]
Thank you @bvaughn 

Sorry just coming back to this.

@bvaughn I will test that again on Monday. Thanks again and thank you @Andarist 

@Sloebel I did not resolve it yet. Just didn't test for it.

**Comment by I-NOZex** [comment]
@bvaughn 
running the vitest in browser mode seems to work, however I have the v3.0.2 of this package, is that expected (is the vitest config still required)?

**Comment by eliasinho** [comment]
Still having this issue using `3.0.6`. Had to manually point the resolution to the browser bundle in my Vitest config:
```typescript
resolve: {
    alias: {
      'react-resizable-panels': path.resolve(
        __dirname,
        './node_modules/react-resizable-panels/dist/react-resizable-panels.browser.development.js',
      ),
    },
  },
```

**Comment by Andarist** [comment]
@eliasinho  Could you prepare a runnable repro case of your problem?
