### ISSUE TITLE
Layout values set to NaN if group is rendered within a hidden container

### ISSUE THREAD

**Issue by songkeys** [bvaughn/react-resizable-panels#536]
Currently migrating from v3 to v4. my code looks like this:

<img width="816" height="412" alt="Image" src="https://github.com/user-attachments/assets/5a588a22-12ba-45c3-8011-ddd6c3483b5e" />

<img width="330" height="103" alt="Image" src="https://github.com/user-attachments/assets/ba396387-1360-4344-8bc5-545cba69f903" />

I copied the base components from shadcn and adapt to v4 changes:

```tsx
'use client'

import { HandGripIcon } from '@hugeicons-pro/core-stroke-rounded'
import type * as React from 'react'
import * as ResizablePrimitive from 'react-resizable-panels'

import { Icon } from '@/components/ui/icon'
import { cn } from '@/lib/utils'

function ResizablePanelGroup({
	className,
	...props
}: React.ComponentProps<typeof ResizablePrimitive.Group>) {
	return (
		<ResizablePrimitive.Group
			data-slot="resizable-panel-group"
			className={cn(
				'flex h-full w-full data-[panel-group-direction=vertical]:flex-col',
				className,
			)}
			{...props}
		/>
	)
}

function ResizablePanel({
	...props
}: React.ComponentProps<typeof ResizablePrimitive.Panel>) {
	return <ResizablePrimitive.Panel data-slot="resizable-panel" {...props} />
}

function ResizableHandle({
	withHandle,
	className,
	...props
}: React.ComponentProps<typeof ResizablePrimitive.Separator> & {
	withHandle?: boolean
}) {
	return (
		<ResizablePrimitive.Separator
			data-slot="resizable-handle"
			className={cn(
				'focus-visible:ring-ring relative flex w-px items-center justify-center after:absolute after:inset-y-0 after:left-1/2 after:w-1 after:-translate-x-1/2 focus-visible:ring-1 focus-visible:ring-offset-1 focus-visible:outline-hidden data-[panel-group-direction=vertical]:h-px data-[panel-group-direction=vertical]:w-full data-[panel-group-direction=vertical]:after:left-0 data-[panel-group-direction=vertical]:after:h-1 data-[panel-group-direction=vertical]:after:w-full data-[panel-group-direction=vertical]:after:translate-x-0 data-[panel-group-direction=vertical]:after:-translate-y-1/2 [&[data-panel-group-direction=vertical]>div]:rotate-90',
				'opacity-20 hover:opacity-80 transition-opacity',
				// "data-[resize-handle-state='hover']:bg-primary transition-colors",
				className,
			)}
			{...props}
		>
			{withHandle && (
				<div className="z-10 flex h-4 w-3 items-center justify-center rounded-xs bg-border">
					<Icon icon={HandGripIcon} className="size-4" />
				</div>
			)}
		</ResizablePrimitive.Separator>
	)
}

export { ResizableHandle, ResizablePanel, ResizablePanelGroup }

```

**Comment by bvaughn** [comment]
I have nothing to do with ShadUI. I would be surprised if they have updated their wrapper to work with version 4 of this library already. When I looked earlier today, they were pinned to version 3.

**Comment by songkeys** [comment]
No. They haven't. I migrated myself. You can see from my snippet - i don't think this NaN comes from the wrapper.

**Comment by bvaughn** [comment]
Share a full, runnable repro then and I’ll take a look.

**Comment by songkeys** [comment]
Sure. I'll do tomorrow. It's too late for me today. My project is too big. It might take some time to extract a minimal repro. Will come to you.

**Comment by bvaughn** [comment]
Understood! Sounds good.

**Comment by bvaughn** [comment]
Related: https://github.com/shadcn-ui/ui/pull/9124

**Comment by songkeys** [comment]
Hi. Please take a look: https://codesandbox.io/p/devbox/7357zv

This doesn't relate to shadcn/ui

Steps to reproduce

  1. Start the dev server and open the browser DevTools console.
  2. On initial load, Tab B is mounted but hidden via display: none.
  3. You should see a log like:
      - [tab b] onLayoutChange { left: NaN, right: NaN }
  4. Click “Tab B” to show it — the layout remains poisoned (still NaN).


This "display:none" behavior works fine in v3 though.

---

edit: `getLayout` and `setLayout` also throw "Group ... not found" error in this case. Previously it's working.

**Comment by bvaughn** [comment]
> ### Devbox not found
> It's likely that the Devbox you're trying to access doesn't exist or you don't have the required permissions to access it.

**Comment by songkeys** [comment]
> > ### Devbox not found
> > It's likely that the Devbox you're trying to access doesn't exist or you don't have the required permissions to access it.

Sorry about this. Just updated the permission

**Comment by bvaughn** [comment]
I see what you mean. The problem is that `Group` can't convert constraints to percentages if it can't measure its own dimensions (and it can't when it's in a hidden subtree). I'm not sure of the best way to fix this, practically. I'll give it some thought.

**Comment by songkeys** [comment]
Is it possible to delay the calculation (and also safely handle `getLayout`) until it is visible by monitoring the visibility? User would only interact when it's visible I think.

**Comment by bvaughn** [comment]
Conceptually, yes, but practically it's more complicated than that. Let me think about it some.

**Comment by bvaughn** [comment]
I think I might be able to leverage the `content-visibility: auto` style and then listen for a "contentvisibilityautostatechange" event on a group as a signal for when it's safe to calculate/recalculate constraints. I think the trickiest part will be deferring the _default layout_ calculation without invalidating some other set of assumptions.

**Comment by bvaughn** [comment]
Actually, I don't think the browser support for that event is good enough to rely on it yet. I think I'm going to require users to hide/show subtrees using [React's `Activity` API](https://react.dev/reference/react/Activity).

I think that's what version 3 of this library relied on, though it didn't have as hard of a constraint since it didn't need to do the mapping of pixels to percentages.

**Comment by jdtzmn** [comment]
@songkeys if it helps, I'm doing the following and it seems to work well.

```typescript
function Layout() {
    const isMd = useMediaMatch(..., default=true)

    return (
        <div>
            <div className="md:hidden">
                {/* mobile UI, no panels */}
            </div>
            <div className="hidden md:block">
                {isMd && (
                    <Group>
                        {/* panels */}
                    </Group>
                )}
            </div>
        </div>
    )
}
```

By always rendering assuming the viewport is medium, I avoid hydration warnings and ensure it re-mounts when the window width changes from mobile to desktop.

**Comment by bvaughn** [comment]
FWIW what I meant by using `Activity` is e.g.
```tsx
import { Activity } from "react";

<Activity mode="hidden"> // or "visible"
  <Group>
    ...
  </Group>
</Activity>
```

**Comment by bvaughn** [comment]
I _think_ #541 should resolve this. Any chance you could try it out and let me know, @songkeys? Here's an alpha build I published for you:

```
npm install  react-resizable-panels@4.0.8-alpha.0
```

**Comment by bvaughn** [comment]
Actually, I think I might have a simpler solution that doesn't require using a newer API like `checkVisibility`:
```
npm install  react-resizable-panels@4.0.8-alpha.2
```

**Comment by bvaughn** [comment]
I'm confident the change in the latest alpha should fix this. I'll publish it as part of `react-resizable-panels@4.0.8` sometime today.

**Comment by bvaughn** [comment]
Fix has been published as part of `react-resizable-panels@4.0.8`

Full release notes at https://github.com/bvaughn/react-resizable-panels/releases/tag/4.0.8

---

❤️ → ☕ [givebrian.coffee](http://givebrian.coffee/)

**Comment by songkeys** [comment]
@bvaughn Thank you for the wonderful fix! Just bought you a coffee. It works good in my reproduction sandbox. :)

One last thing might be that `getLayout`/`setLayout` is still not safely delayed?

https://codesandbox.io/p/devbox/resizable-repro-forked-qwyqmm?workspaceId=ws_TWhT4rma3bLZV1dSe1y2NB

**Comment by bvaughn** [comment]
You're welcome :) thank you fro the coffee.

> One last thing might be that `getLayout`/`setLayout` is still not safely delayed?

That error ("Group <id> not found") indicates that the group hasn't mounted yet, which I think kind of makes sense but I can also see how that could be confusing. What would you expect to happen for a group that had mounted within a hidden subtree?

**Comment by songkeys** [comment]
> That error ("Group not found") indicates that the group hasn't mounted yet, which I think kind of makes sense but I can also see how that could be confusing. What would you expect to happen for a group that had mounted within a hidden subtree?

This makes sense since users can wrap it with try catch to handle it. I think it won't be a much problem!

If doing in library side, I think the `getLayout` should return 0 (as it is indeed 0 if hidden) and `setLayout` should pend this action and wait until it's shown to take effect?

**Comment by bvaughn** [comment]
> If doing in library side, I think the `getLayout` should return 0 (as it is indeed 0 if hidden) and `setLayout` should pend this action and wait until it's shown to take effect?

I don't think it would make sense to return 0 for a layout, since layout is a map of panel id to %. I'm also not sure I can easily defer the layout until the Group has later been mounted. I think that is probably more of an edge than something I want to support.

Maybe I can improve the error message returned in this case to clarify that the group was rendered within a hidden DOM tree and so it can't be interactive with yet.

**Comment by bvaughn** [comment]
#549 makes a few more improvements here:

- Defer the initial call to `onLayoutChange` until the Group is visible; (we can't validate layouts prior to that so it doesn't make sense to potentially call the change handler and save a layout)
- Trying to interact with the imperative API before a Group is visible doesn't error, but `getLayout` will return an empty layout (`{}`) and calling `setLayout` will do nothing

**Comment by bvaughn** [comment]
The improvements above have been published as `react-resizable-panels@4.0.9`

Thanks for the feedback!

---

❤️ → ☕ [givebrian.coffee](http://givebrian.coffee/)
