### ISSUE TITLE
Iframe inside panels

### ISSUE THREAD

**Issue by danilowoz** [bvaughn/react-resizable-panels#64]
I noted that the drag event doesn't work correctly when there's an iframe inside a Panel. It could be because the dragging listener is on the main window, and it doesn't consider the other window, which is the iframe.

Here's a screenrecording ([sandbox](https://23rsmw.csb.app/)):

https://user-images.githubusercontent.com/4838076/210798821-09c74e1e-2f84-43ac-9865-c4d76d0a43b4.mov

**Possible solution**

It just works if you set `point-events: none` on the iframe. 

https://user-images.githubusercontent.com/4838076/210800180-9c0c4227-1e34-491a-a7b1-902fe001b389.mov

**Comment by bvaughn** [comment]
@danilowoz I think #66 should resolve this issue.

**Comment by bvaughn** [comment]
v0.0.29 just released

**Comment by chdominguez** [comment]
This happens on v0.0.51. I used `disablePointerEventsDuringResize` in the panel group but the bug is still present.
